# -*- coding: utf-8 -*-
"""Booked Visits for Self-Guided Workouts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wyN8xVyVPFW4GeRS-08SvGzjpPY54cPq

Booked Visits for Self-Guided Workouts

Integration:Amazon Redshift Purpose:Contact Data
"""

SELECT memberid as member_id,
case when max(starttimelocal) > max(current_timestamp) then true else false end as has_upcoming_visit
from simon.event_bav
group by memberid