# -*- coding: utf-8 -*-
"""Cancel Membership.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tLfkSXVq53tAT8XZKacEBZmR6vDXd5eg

Cancel Membership

Integration:Amazon Redshift Purpose:Contact Event Data
"""

with valid_data as (
select 
  member_id,
  member_id as unique_id,
  cancellation_date as ts
from
  member_contract_tenure
  where cancellation_date is not null
  and cancellation_date <= DATE_ADD('year', 5, CURRENT_DATE)
  and cancellation_date > TO_DATE ('01 Jan 1970', 'DD Mon YYYY')
)

select
  member_id,
  unique_id,
  extract(epoch from date_trunc('second', ts)) as ts
from
  valid_data