# -*- coding: utf-8 -*-
"""Equinox Membership Start New Contract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vj70qlTBfFhx8xn8xju-up1XCbTbQvg6
"""



"""Equinox Membership Start New Contract

Integration:Amazon RedshiftPurpose:Contact Event Data
"""

/*Purpose: Another definition of membership start that will capture both 
winbacks (previously canceled members that restart their membership) and new members.
Equinox is launching a winback campaign and would like to be able to use this to measure success.
This will be used to set up a goal event for winbacks
Removed invalid dates so that Simon can process them
*/

with valid_data as (
select 
   member_id,
   member_id as unique_id,
       CASE            
      WHEN member_since_date LIKE '%-02-29%' THEN NULL
      WHEN member_since_date LIKE '%-02-30%' THEN NULL
      WHEN member_since_date LIKE '%-02-31%' THEN NULL           
      WHEN member_since_date LIKE '%-06-31%' THEN NULL
      WHEN member_since_date LIKE '%-04-31%' THEN NULL
      WHEN member_since_date LIKE '%-09-31%' THEN NULL           
      WHEN member_since_date LIKE '%-11-31%' THEN NULL
      else member_since_date
      end as ts
 from
   member_contract_tenure
 where
   member_since_date != '2047-01-01 00:00:00'
   AND member_since_date >= '1970-01-01 00:00:00'
   AND member_since_date <= '2025-01-01 00:00:00'
   AND member_since_date not like '%02-29%'
   AND member_since_date not like '%02-30%'
   AND member_since_date not like '%02-31%'
   AND member_since_date not like '%06-31%'
   AND member_since_date not like '%04-31%'
   AND member_since_date not like '%09-31%'
   AND member_since_date not like '%11-31%'
   
 )

 select
   member_id,
   unique_id,
   extract(epoch from ts) as ts
 from
   valid_data