# -*- coding: utf-8 -*-
"""Equinox Weekly Email Report.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EZmZA5Z_62GKuBRfRPV9BYA-WN4Fpjr7

Equinox Weekly Email Report
Athena, Other purpose 
https://equinox.simondata.com/queries/7466/details/editor?page=10
"""

WITH 

open_engagement as (
  SELECT
    s.emailname,
    substr(s.eventdate,1,10) AS day,
    cast(count(distinct s.email) as double) as total_sends,
    cast(count(o.email) as double) as total_opens,
    cast(count(distinct o.email) as double) as total_unique_opens
  FROM
    et_sends_deduped s left join et_opens_deduped o on 
      s.emailname = o.emailname
      AND s.email = o.email
      AND s.sendid = o.sendid
  WHERE
    s.emailname is not null AND length(s.emailname) > 2 AND s.email not like '%@equinox%' AND
    (date_diff('day', Cast(Substr(Replace(s.eventdate, 'T', ' '), 1, 19) AS TIMESTAMP), Cast(Substr(Replace(o.eventdate, 'T', ' '), 1, 19) AS TIMESTAMP)) <= 2
    OR o.eventdate is null)
  GROUP BY
    1,2
),

click_engagement as (
  SELECT
    s.emailname,
    substr(s.eventdate,1,10) AS day,
    cast(count(c.email) as double) as total_clicks,
    cast(count(distinct c.email) as double) as total_unique_clicks
  FROM
    et_sends_deduped s left join et_clicks_deduped c on
      s.emailname = c.emailname
      AND s.email = c.email
      AND s.sendid = c.sendid 
  WHERE
    s.emailname is not null AND length(s.emailname) > 2 AND s.email not like '%@equinox%' AND
    (date_diff('day', Cast(Substr(Replace(s.eventdate, 'T', ' '), 1, 19) AS TIMESTAMP), Cast(Substr(Replace(c.eventdate, 'T', ' '), 1, 19) AS TIMESTAMP)) <= 2
    OR c.eventdate is null)
  GROUP BY
    1,2
),

send_unsub_engagement as (
  SELECT
    s.emailname,
    substr(s.eventdate,1,10) AS day,
    cast(count(distinct s.email) as double) as total_sends,
    cast(count(distinct u.email) as double) as total_unsubscribes
  FROM
    et_sends_deduped s left join et_unsubscribes_deduped u on
      s.emailname = u.emailname
      AND s.email = u.email
  WHERE
    s.emailname is not null AND length(s.emailname) > 2 AND s.email not like '%@equinox%' AND
    (date_diff('day', Cast(Substr(Replace(s.eventdate, 'T', ' '), 1, 19) AS TIMESTAMP), Cast(Substr(Replace(u.eventdate, 'T', ' '), 1, 19) AS TIMESTAMP)) <= 30
    OR u.eventdate is null)
  GROUP BY
    1,2
),

email_engagement as (
  SELECT
    sbu.emailname,
    sbu.day as day,
    sbu.total_sends as total_sends,
    oe.total_opens as total_opens,
    oe.total_unique_opens as total_unique_opens,
    ce.total_clicks as total_clicks,
    ce.total_unique_clicks as total_unique_clicks,
    sbu.total_unsubscribes as total_unsubscribes
  FROM
    send_unsub_engagement sbu LEFT JOIN open_engagement oe ON
      sbu.emailname = oe.emailname
      AND sbu.day = oe.day
    LEFT JOIN click_engagement ce ON
      sbu.emailname = ce.emailname
      AND sbu.day = ce.day
)

SELECT 
  e.emailname as email,
  e.day,
  e.total_sends, 
  e.total_unique_opens, 
  e.total_unique_opens / e.total_sends as unique_open_rate, 
  e.total_opens, 
  e.total_opens / e.total_sends as total_open_rate, 
  e.total_unique_clicks, 
  e.total_unique_clicks / e.total_sends as unique_click_rate, 
  e.total_clicks, 
  e.total_clicks / e.total_sends as total_click_rate, 
  e.total_unsubscribes
FROM 
  email_engagement e
ORDER BY 
  e.day desc, 
  e.emailname asc