# -*- coding: utf-8 -*-
"""ET Unsubscribes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UyVQiRHFklfxJSxfOOt0x_BRNhIKrbrX

ET Unsubscribes

Integration:PrestoPurpose:Contact Event Data
"""

SELECT 
  email
  ,emailname
  --,sendid
  ,cast(to_unixtime(try(date_add('hour', 6, from_iso8601_timestamp(replace(substr(eventdate,1,19), ' ', 'T'))))) as bigint) as ts
  --,event
  ,CONCAT(email,emailname,eventdate) AS unique_id
FROM et_unsubscribes_deduped

