# -*- coding: utf-8 -*-
"""On Freeze to Active.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19666yZd1eo5yzucfnROAhVFw41UPyRCX

On Freeze to Active

Integration:Simon Snowflake Purpose:Contact Event Data
"""

/* 
  The purpose of this report is to track members who moved from 'On Freeze' to 'Active'.
  Each of thses 2 audiences is connected to a tracking flow with a 'Do Nothing' action.
  The use case for this dataset is to create a goal event of when someone that was previousely 'On Freeze' becomes 'Active'.
*/

/*First, pull the data for each member that was removed from the 'On Freeze' flow */
with on_freeze_removes as (
  select * from prod.flow_actions__latest 
  where campaign_id = '587336' and action = 'remove'
)

/*Next, pull the data for each member that was added to the 'Active' flow */
,active_adds as (
  select * from prod.flow_actions__latest
  where campaign_id = '587334' and action = 'add'
)


/*
  Lastly, filter for members who were both removed from the 'On Freeze' flow and added to the 'Active' flow.
  Note the timestamp field for when they were added.
  Make sure the 'add' to the active segment happens after the 'remove' from the on freeze.
*/

select a.native_id as member_id, concat(a.native_id, a.ts) as unique_id, a.ts ts_freeze_to_active
from on_freeze_removes f left join active_adds a on f.native_id = a.native_id
where f.action = 'remove' and a.action = 'add'
and f.ts < a.ts