# -*- coding: utf-8 -*-
"""Pre-COVID Feb GF Class Taken.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X_FxL5EQ6FhvYG4w7PkjdXhwpvAT9V_N

Pre-covid GF Class Taken

Integration:Amazon Redshift Purpose:Contact Data
"""

/*
   flag all classes that occurred during the month of february (2/1/20-2/29/20) 
   that were not cancelled by the member (based on booking_cancelled_date) and 
   were actually taken (based on the taken_count flag)
*/
with feb_filter as                                                                                                                   
(select s.member_id, s.class_start_date_local_ts, s.booking_cancelled_date_local_ts, s.taken_count, 1 as is_feb_2020   
from simon.event_group_fitness s
where booking_cancelled_date_local_ts is null 
  and taken_count=1 
  and cast(s.class_start_date_local_ts as date) >= '2020-02-01' and cast(s.class_start_date_local_ts as date) <= '2020-02-29'
)

/* dedup so output contains all member_ids that took at least 1 class in feb 2020 */
select member_id, max(is_feb_2020) as at_least_1_class_feb
from feb_filter
group by 1