# -*- coding: utf-8 -*-
"""Top GF Class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yUW_WAI2aDG8XIV8PcpPp9wliI_qV1-t

Top GF Class

Integration:Amazon Redshift Purpose:Contact Data
"""

/* Identify which group fitness class is taken the most by each member */

/* filter GF class detail to only include classes taken. a filter was also applied to a specific date range for COVID analysis purposes */
with date_filter as                                                                                                                   
(select class_name, class_instance_id, s.member_id, s.class_start_date_local_ts, s.booking_cancelled_date_local_ts, s.taken_count, 1 as is_date_range   
from simon.event_group_fitness s
where booking_cancelled_date_local_ts is null 
  and taken_count=1 
  and cast(s.class_start_date_local_ts as date) >= '2019-03-01' and cast(s.class_start_date_local_ts as date) <= '2020-02-29'
),

/* count the number of times each class is taken by each member */
class_counts as (
select member_id, class_name, count(*) as class_count
from date_filter
group by 1,2
),

/* rank each class for each member based on their count */
class_ranks as(
select member_id, class_name, class_count, row_number() over (partition by member_id order by class_count desc) as class_rank
from class_counts
)

/* output only the top ranked class for each member_id */
select member_id, class_name as top_gf_class
from class_ranks
where class_rank=1 and class_count >= 3 --only include members that have taken their top class at least 3 times