# -*- coding: utf-8 -*-
"""Total GF Classes Taken.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jvC_DTarruBXjDhzCERohVTAPDM9Zwhv

Total GF Classes Taken

Integration:Amazon Redshift Purpose:Contact Data
"""

/* Goal: equinox is designing a personalized email that summarizes activity of new members that will be triggered after the first 30 days of their membership.
This query pulls a custom attribute that tells us the total number of group fitness classes taken since joining (their member_since_date) */

/* pulls classes that started on or after the member's most recent membership date*/

with recent_classes as (
select s.member_id, class_instance_id, taken_count,
case when cast(member_since_date as date) <= cast(class_start_date_local_ts as date) then 1 else 0 end as is_recent_class
from simon.event_group_fitness s
left join member_contract_tenure t
on s.member_id=t.member_id
)

/* counts all classes per member */
/* filters for classes that are recent and classes that were taken */

select member_id, count(class_instance_id) as total_gf_classes_taken_count
from recent_classes
where taken_count = 1 and is_recent_class = 1
group by 1