# -*- coding: utf-8 -*-
"""SMS Click Events.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uiqvbA-4NWFbhA4lFMOZ_kZGwgIipOHl

SMS Click Events

Integration:Presto Purpose:Contact Event Data
"""

/*Goal: a contact event dataset for records where a text message link was clicked*/

/*pulls in the time the message was sent, the time the link was clicked, the message name, type, and subtype*/
/*changes the format of the phone number to correspond with the Results Attentive Identity dataset*/
/*creates a unique identifier based on phone number and time the link was clicked*/

select 
substr(phone, 3) as phone_number,
case when message_start like '%-%' then cast(to_unixtime(date_parse(message_start, '%Y-%m-%d %H:%i:%s')) as bigint) end as message_start,
cast(to_unixtime(from_iso8601_timestamp(timestamp)) as bigint) as created_timestamp,
CONCAT(substr(phone, 3) ,timestamp) as unique_id,
message_name,
message_subtype,
message_type
from attentive_daily_detail_dl
where type = 'MESSAGE_LINK_CLICK'